tap "shivammathur/php"
tap "symfony-cli/tap"
tap "dunglas/frankenphp"
tap "FelixKratz/formulae"

cask_args appdir: "~/Applications"

# Web browsers
cask "brave-browser"
cask "chromedriver"
cask "obsidian"
cask "font-meslo-lg-nerd-font"
cask "font-hack-nerd-font"
cask "firefox"
cask "ghostty"
cask "raycast"
cask "pgadmin4"
# cask "google-chrome" -- already installed by Workspace One, skipping in pro env.

# Code related tools
cask "android-studio"
cask "nikitabobko/tap/aerospace"
cask "bruno"
cask "copilot-cli"
cask "deezer"
cask "gcloud-cli"
cask "mitmproxy"
cask "neovide-app"
cask "postgres-app"
cask "visual-studio-code"

# General tools
cask "calibre"
cask "figma"
cask "imageoptim"
cask "handbrake-app"
cask "keepingyouawake"
cask "localsend"
cask "raindropio"
cask "ticktick"
cask "vlc"

# And the brew formulaes
brew "act"
brew "ansible"
brew "awscli"
brew "bat"
brew "ca-certificates"
brew "cloc"
brew "cmake"
brew "cocoapods"
brew "colima"
brew "coreutils"
brew "direnv"
brew "dnsmasq"
brew "dust"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "eza"
brew "fd"
brew "fzf"
brew "ffmpeg"
brew "gemini-cli"
brew "git"
brew "gh"
brew "gnu-sed"
brew "go"
brew "go-task"
brew "htop"
brew "hub"
brew "httpie"
brew "inetutils"
brew "jenv"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lazysql"
brew "kubernetes-cli"
brew "maven"
brew "mysql@8.0"
brew "mysql-client@8.0"
brew "mtr"
brew "nvim"
brew "ncdu"
brew "nss"
brew "openjdk@11"
brew "opencode"
brew "opensearch"
brew "protobuf"
brew "pv"
brew "scw" # Scaleway cli
brew "sd"
brew "sketchybar"
brew "starship"
brew "rclone"
brew "terraform"
brew "tmux"
brew "tree"
brew "rabbitmq"
brew "rabbitmq-c"
brew "redis"
brew "ripgrep"
brew "rtk"
brew "python@3.10"
brew "qemu"
brew "volta"
brew "watch"
brew "watchman"
brew "wget"
brew "uv"  # python tool, required for Senera MCP
brew "yt-dlp"
brew "zoxide"
brew "zsh"

# PHP related stuff
brew "symfony-cli/tap/symfony-cli"
brew "shivammathur/php/php@8.3"
brew "shivammathur/php/php@8.4"

