tap "shivammathur/php", trusted: true
tap "symfony-cli/tap", trusted: true
tap "dunglas/frankenphp", trusted: true
tap "FelixKratz/formulae", trusted: true
tap "nikitabobko/tap", trusted: true

cask_args appdir: "~/Applications"

# Web browsers
cask "aerospace"
cask "android-studio"
cask "brave-browser"
cask "bruno"
cask "chromedriver"
cask "copilot-cli"
cask "dbeaver-community"
cask "font-meslo-lg-nerd-font"
cask "font-hack-nerd-font"
cask "firefox"
cask "ghostty"
cask "mitmproxy"
cask "obsidian"
cask "pgadmin4"
cask "raycast"
cask "rancher"
cask "signal"
cask "gcloud-cli"
cask "neovide-app"
cask "postgres-app"

# General tools
cask "figma"
cask "imageoptim"
cask "handbrake-app"
cask "keepingyouawake"
cask "localsend"
cask "raindropio"
cask "ticktick"
cask "vlc"

# And the brew formulaes
brew "act"
brew "ansible"
brew "awscli"
brew "bat"
brew "ca-certificates"
brew "cloc"
brew "cmake"
brew "colima"
brew "coreutils"
brew "direnv"
brew "dust"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "eza"
brew "fd"
brew "fzf"
brew "ffmpeg"
brew "git"
brew "gh"
brew "gnu-sed"
brew "go"
brew "go-task"
brew "htop"
brew "hub"
brew "httpie"
brew "inetutils"
brew "jenv"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lazysql"
brew "kubernetes-cli"
brew "mago"
brew "maven"
brew "mysql@8.0"
brew "mysql-client@8.0"
brew "mtr"
brew "nvim"
brew "ncdu"
brew "nss"
brew "ollama"
brew "openjdk@11"
brew "opencode"
brew "opensearch"
brew "phpantom-lsp"
brew "pi-coding-agent"
brew "pie"
brew "protobuf"
brew "pv"
brew "scw" # Scaleway cli
brew "sd"
brew "sketchybar"
brew "starship"
brew "rclone"
brew "terraform"
brew "tmux"
brew "tree"
brew "rabbitmq"
brew "rabbitmq-c"
brew "redis"
brew "ripgrep"
brew "rtk"
brew "pkg-config"
brew "python@3.10"
brew "qemu"
brew "volta"
brew "watch"
brew "watchman"
brew "wget"
brew "uv"  # python tool, required for Senera MCP
brew "yt-dlp"
brew "zizmor"
brew "zlib"
brew "zoxide"
brew "zsh"

# PHP related stuff
brew "symfony-cli/tap/symfony-cli"
brew "shivammathur/php/php@8.4"
