require('plugins-setup')
require('core')
require('keymaps')
require('colorscheme')

require('plugins/comment')
require('plugins/gitsigns')
require('plugins/lualine')
require('plugins/nvim-tree')
require('plugins/treesitter')
require('plugins/telescope')
require('plugins/lsp-zero')
