tap "homebrew/cask"

# Web browsers
cask "brave-browser"
cask "firefox"
cask "google-chrome"

# Code related tools
cask "jetbrains-toolbox"
cask "dbeaver-community"
cask "postman"
cask "visual-studio-code"

# General tools
cask "dozer"
cask "libreoffice"
cask "notion"
cask "keepassxc"
cask "keepingyouawake"
cask "slack"
cask "spotify"
cask "rectangle"
cask "ticktick"
